services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 CRM_app.wsgi:application

    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/CRM_app/static
      - bd_volume:/app/CRM_app/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/CRM_app/static
    depends_on:
      - web

volumes:
  static_volume:
  bd_volume: