# Generated by Django 4.2.16 on 2025-01-19 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_companies_main_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование пункта ошибки')),
                ('worth', models.PositiveSmallIntegerField(choices=[(5, '5'), (15, '15'), (25, '25'), (50, '50'), (100, '100')], verbose_name='Вес ошибки')),
            ],
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Категория ошибки')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suberrors', to='checklists.suberrors', verbose_name='Пункт')),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата проверки')),
                ('type', models.CharField(choices=[('звонок', 'звонок'), ('письма', 'письма')], max_length=12, verbose_name='Тип обращения')),
                ('count', models.IntegerField(default=0, verbose_name='Количество прослушано')),
                ('call_datetime', models.DateTimeField(default=None, verbose_name='Дата и время обращения')),
                ('call_id', models.TextField(max_length=500, verbose_name='id звонка')),
                ('first_comm', models.TextField(blank=True, max_length=1500, verbose_name='Комментарий 1')),
                ('second_comm', models.TextField(blank=True, max_length=1500, verbose_name='Комментарий 2')),
                ('third_comm', models.TextField(blank=True, max_length=1500, verbose_name='Комментарий 3')),
                ('forty_comm', models.TextField(blank=True, max_length=1500, verbose_name='Комментарий 4')),
                ('fifty_comm', models.TextField(blank=True, max_length=1500, verbose_name='Комментарий 5')),
                ('sixty_comm', models.TextField(blank=True, max_length=1500, verbose_name='Комментарий 6')),
                ('result', models.CharField(max_length=10)),
                ('comment', models.TextField(max_length=1500, verbose_name='Комментарий')),
                ('decision', models.CharField(choices=[('Удоветворено', 'Удоветворено'), ('Отказано', 'Отказано')], max_length=1500, verbose_name='Решение ДМ')),
                ('comment_court', models.TextField(blank=True, max_length=1500, verbose_name='Комментарий к решению')),
                ('claim', models.BooleanField(choices=[(True, 'Жалоба обоснованная'), (False, 'Жалоба не обоснованная')], verbose_name='Жалоба')),
                ('claim_nubmer', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Номер жалобы')),
                ('date_incident', models.DateField(default=None, null=True, verbose_name='Дата ошибки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.companies', verbose_name='Компания')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controller', to=settings.AUTH_USER_MODEL, verbose_name='Контролер')),
                ('fifty_err', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiftyerror', to='checklists.errors', verbose_name='Категория 5')),
                ('first_err', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firsterror', to='checklists.errors', verbose_name='Категория 1')),
                ('forty_err', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fortyerror', to='checklists.errors', verbose_name='Категория 4')),
                ('line', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='profiles.lines', verbose_name='Линия')),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_name', to=settings.AUTH_USER_MODEL, verbose_name='ФИ оператора')),
                ('second_err', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seconderror', to='checklists.errors', verbose_name='Категория 2')),
                ('sixty_err', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sixtyerror', to='checklists.errors', verbose_name='Категория 6')),
                ('third_err', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thirderror', to='checklists.errors', verbose_name='Категория 3')),
            ],
        ),
    ]
