# Generated by Django 4.2.16 on 2025-01-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Errors',
            new_name='Error',
        ),
        migrations.RenameModel(
            old_name='SubErrors',
            new_name='SubError',
        ),
    ]
