# Generated by Django 4.2.16 on 2025-01-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_rename_errors_error_rename_suberrors_suberror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='attachment',
        ),
        migrations.AddField(
            model_name='suberror',
            name='attachment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='suberrors', to='checklists.error', verbose_name='Пункт'),
            preserve_default=False,
        ),
    ]
