# Generated by Django 4.2.16 on 2025-01-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_remove_error_attachment_suberror_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Категория ошибки')),
                ('worth', models.PositiveSmallIntegerField(choices=[(5, '5'), (15, '15'), (25, '25'), (50, '50'), (100, '100')], verbose_name='Вес ошибки')),
            ],
        ),
        migrations.CreateModel(
            name='SubMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование пункта ошибки')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suberrors', to='checklists.mistake', verbose_name='Пункт')),
            ],
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='type',
            new_name='type_appeal',
        ),
        migrations.DeleteModel(
            name='SubError',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='fifty_err',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiftyerror', to='checklists.submistake', verbose_name='Категория 5'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='first_err',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firsterror', to='checklists.submistake', verbose_name='Категория 1'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='forty_err',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fortyerror', to='checklists.submistake', verbose_name='Категория 4'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='second_err',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seconderror', to='checklists.submistake', verbose_name='Категория 2'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sixty_err',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sixtyerror', to='checklists.submistake', verbose_name='Категория 6'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='third_err',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thirderror', to='checklists.submistake', verbose_name='Категория 3'),
        ),
        migrations.DeleteModel(
            name='Error',
        ),
    ]
