# Generated by Django 4.2.16 on 2025-01-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_mistake_submistake_rename_type_checklist_type_appeal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='fifty_err',
            new_name='fifty_miss',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='first_err',
            new_name='first_miss',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='forty_err',
            new_name='forty_miss',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='second_err',
            new_name='second_miss',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='sixty_err',
            new_name='sixty_miss',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='third_err',
            new_name='third_miss',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='date_incident',
        ),
    ]
