# Generated by Django 4.2.16 on 2025-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_rename_fifty_err_checklist_fifty_miss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='just',
            field=models.BooleanField(default=False, verbose_name='Обоснованность жалобы'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='claim',
            field=models.BooleanField(default=False, verbose_name='Жалоба'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='comment',
            field=models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='Комментарий компании'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='comment_court',
            field=models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='Комментарий к решению'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='decision',
            field=models.CharField(blank=True, choices=[('Удоветворено', 'Удоветворено'), ('Отказано', 'Отказано'), (None, None)], default=None, max_length=1500, null=True, verbose_name='Решение ДМ'),
        ),
    ]
