# Generated by Django 4.2.16 on 2025-01-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_alter_checklist_second_miss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='second_miss',
            field=models.ForeignKey(limit_choices_to={'attachment': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='seconderror', to='checklists.submistake', verbose_name='Категория 2'),
        ),
    ]
