# Generated by Django 4.2.16 on 2025-01-25 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_companies_main_company'),
        ('checklists', '0011_alter_checklist_second_miss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='call_datetime',
        ),
        migrations.AddField(
            model_name='checklist',
            name='call_date',
            field=models.DateField(default=None, verbose_name='Дата обращения'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='call_time',
            field=models.TimeField(default=None, verbose_name='Время обращения'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='profiles.lines', verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='operator_name',
            field=models.ForeignKey(limit_choices_to={'profile__post': 'Operator'}, on_delete=django.db.models.deletion.PROTECT, related_name='operator_name', to=settings.AUTH_USER_MODEL, verbose_name='ФИ оператора'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='result',
            field=models.PositiveSmallIntegerField(blank=True, default=100, max_length=10, verbose_name='Оценка'),
        ),
    ]
