# Generated by Django 4.2.16 on 2025-01-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_remove_checklist_call_datetime_checklist_call_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='claim_nubmer',
            new_name='claim_number',
        ),
    ]
