# Generated by Django 4.2.16 on 2025-01-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0013_rename_claim_nubmer_checklist_claim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='fifty_miss',
            field=models.ForeignKey(default='1', limit_choices_to={'attachment': 5}, on_delete=django.db.models.deletion.PROTECT, related_name='fiftyerror', to='checklists.submistake', verbose_name='Категория 5'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='first_miss',
            field=models.ForeignKey(default='1', limit_choices_to={'attachment': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='firsterror', to='checklists.submistake', verbose_name='Категория 1'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='forty_miss',
            field=models.ForeignKey(default='1', limit_choices_to={'attachment': 4}, on_delete=django.db.models.deletion.PROTECT, related_name='fortyerror', to='checklists.submistake', verbose_name='Категория 4'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='second_miss',
            field=models.ForeignKey(default='1', limit_choices_to={'attachment': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='seconderror', to='checklists.submistake', verbose_name='Категория 2'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sixty_miss',
            field=models.ForeignKey(default='1', limit_choices_to={'attachment': 6}, on_delete=django.db.models.deletion.PROTECT, related_name='sixtyerror', to='checklists.submistake', verbose_name='Категория 6'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='third_miss',
            field=models.ForeignKey(default='1', limit_choices_to={'attachment': 3}, on_delete=django.db.models.deletion.PROTECT, related_name='thirderror', to='checklists.submistake', verbose_name='Категория 3'),
        ),
    ]
