# Generated by Django 4.2.16 on 2025-01-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_alter_checklist_result'),
        ('checklists', '0014_alter_checklist_fifty_miss_and_more'),
    ]

    operations = [
    ]
