# Generated by Django 4.2.16 on 2025-01-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0014_alter_checklist_fifty_miss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='call_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Время обращения'),
        ),
    ]
