# Generated by Django 4.2.16 on 2025-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0015_merge_20250125_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='call_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Время обращения'),
        ),
    ]
