# Generated by Django 4.2.16 on 2025-01-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0015_alter_checklist_call_time'),
        ('checklists', '0016_alter_checklist_call_time'),
    ]

    operations = [
    ]
