# Generated by Django 4.2.16 on 2025-02-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0016_alter_checklist_result'),
        ('checklists', '0017_merge_20250127_2026'),
    ]

    operations = [
    ]
