# Generated by Django 4.2.16 on 2025-02-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0018_merge_20250207_1723'),
        ('checklists', '0018_merge_20250207_2010'),
    ]

    operations = [
    ]
