# Generated by Django 4.2.16 on 2025-02-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_companies_main_company'),
        ('checklists', '0019_merge_20250207_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Проверку', 'verbose_name_plural': 'Чек лист'},
        ),
        migrations.AlterModelOptions(
            name='mistake',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункт'},
        ),
        migrations.AlterModelOptions(
            name='submistake',
            options={'verbose_name': 'Подпункт', 'verbose_name_plural': 'Подпункт'},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='line',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.lines', verbose_name='Линия'),
        ),
    ]
