# Generated by Django 4.2.16 on 2024-12-10 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_exam', models.DateField(validators=[testing.models.validate_date_exam], verbose_name='Дата зачета')),
                ('name_intern', models.CharField(max_length=60, validators=[testing.models.validate_name_intern], verbose_name='Фамилия Имя стажера')),
                ('training_form', models.CharField(choices=[('ВО', 'ВО'), ('Универсал', 'Универсал')], max_length=60, verbose_name='Форма обучения')),
                ('try_count', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Попытка')),
                ('time_exam', models.TimeField(blank=True, default='00:00', verbose_name='Время зачета')),
                ('result_exam', models.CharField(blank=True, choices=[('Не допущен', 'Не допущен'), ('Допущен', 'Допущен'), ('Неявка', 'Неявка'), ('Отмена', 'Отмена'), ('Не состоялось', 'Не состоялось')], default='', max_length=25, verbose_name='Результат')),
                ('comment_exam', models.TextField(blank=True, max_length=2000, verbose_name='комментарий')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='profiles.companies', verbose_name='Компания')),
                ('internal_test_examiner', models.ForeignKey(limit_choices_to={'post': 'admin'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_test_examiner', to=settings.AUTH_USER_MODEL, verbose_name='ФИ принимающего внутреннее ТЗ')),
                ('name_examiner', models.ForeignKey(blank=True, limit_choices_to={'post': 'OKK'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name_examiner', to=settings.AUTH_USER_MODEL, verbose_name='ФИ сотрудника')),
                ('name_train', models.ForeignKey(limit_choices_to={'post': 'admin'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name_train', to=settings.AUTH_USER_MODEL, verbose_name='ФИ обучающего/обучающих')),
            ],
            options={
                'verbose_name': 'Зачет',
                'verbose_name_plural': 'Зачеты',
                'unique_together': {('date_exam', 'time_exam', 'name_examiner')},
            },
        ),
    ]
