# Generated by Django 4.2.16 on 2025-02-10 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0004_alter_exam_date_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='internal_test_examiner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='internal_test_examiner', to=settings.AUTH_USER_MODEL, verbose_name='ФИ принимающего внутреннее ТЗ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='name_train',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='name_train', to=settings.AUTH_USER_MODEL, verbose_name='ФИ обучающего/обучающих'),
            preserve_default=False,
        ),
    ]
