name: CRM web app CI

on:
  push:
    branches:
      - dev_backend
      - dev_frontend
      - test_branch
  pull_request:
    - main
    - dev_main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v2

      - name: Set up Python
        uses: action/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          cd CRM_app
          python manage.py migrate

      - name: Run test
        run: |
          cd CRM_app
          python manage.py test testing.tests
          python manage.py test checklists.tests

      - name: Build frontend
        run: |
          cd my-app
          npm install
          npm run build