# Generated by Django 4.2.16 on 2024-12-10 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Компания')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Компанию',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_line', models.CharField(max_length=24, verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Линию',
                'verbose_name_plural': 'Линии',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, null=True, verbose_name='ФИ сотрудника')),
                ('post', models.CharField(blank=True, choices=[('OKK', 'OKK'), ('GPH', 'GPH'), ('Admin', 'Admin'), ('Operator', 'Operator')], max_length=20, null=True, verbose_name='Должность')),
                ('work_start_date', models.DateField(auto_now_add=True, verbose_name='Дата выхода в линию')),
                ('operator_type', models.CharField(blank=True, choices=[('ВО', 'ВО'), ('ГЛ', 'ГЛ'), ('Ночной ВО', 'Ночной ВО'), ('Стажер', 'Стажер')], max_length=36, null=True, verbose_name='Тип оператора')),
                ('status', models.CharField(choices=[('Работает', 'Работает'), ('Уволен', 'Уволен'), ('В декрете', 'В декрете'), ('На больничном', 'На больничном'), ('б/с', 'б/с')], default='Работает', max_length=16, verbose_name='Статус сотрудника')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='profiles.companies', verbose_name='Компания')),
                ('lines', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.lines')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
