# Generated by Django 4.2.16 on 2024-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_company_alter_profile_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='main_company',
            field=models.BooleanField(default=False),
        ),
    ]
